### PR TITLE
updates paths for faucet 1.7, closes #67

### LINKED ISSUE #67: faucet 1.7
etc/ryu/faucet -> etc/faucet

### PR DESCRIPTION
**Pull request by cglewis**

### CODE REVIEW

**Comment by cglewis** [comment]
oops, didn't see that you already had these changes in #72 - feel free to close if you want instead.

**Comment by Bairdo** [comment]
Thanks,
I'm trying to get in the habit of smaller PRs so i'll merge this one. 

Could you just fix the conflict in requirements.txt, i've just removed a couple of packages.

**Comment by cglewis** [comment]
fixed.

**Comment by Bairdo** [comment]
thank you

**Pull request merged**
